# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbscan_e <- function(edges, eps, minPts, verbose) {
    .Call('largeVis_dbscan_e', PACKAGE = 'largeVis', edges, eps, minPts, verbose)
}

dbscan_ed <- function(edges, data, eps, minPts, verbose) {
    .Call('largeVis_dbscan_ed', PACKAGE = 'largeVis', edges, data, eps, minPts, verbose)
}

dbscan_nd <- function(neighbors, data, eps, minPts, verbose) {
    .Call('largeVis_dbscan_nd', PACKAGE = 'largeVis', neighbors, data, eps, minPts, verbose)
}

optics_e <- function(edges, eps, minPts, verbose) {
    .Call('largeVis_optics_e', PACKAGE = 'largeVis', edges, eps, minPts, verbose)
}

optics_ed <- function(edges, data, eps, minPts, verbose) {
    .Call('largeVis_optics_ed', PACKAGE = 'largeVis', edges, data, eps, minPts, verbose)
}

optics_nd <- function(neighbors, data, eps, minPts, verbose) {
    .Call('largeVis_optics_nd', PACKAGE = 'largeVis', neighbors, data, eps, minPts, verbose)
}

silhouetteDbscan <- function(edges, sil) {
    invisible(.Call('largeVis_silhouetteDbscan', PACKAGE = 'largeVis', edges, sil))
}

searchTrees <- function(threshold, n_trees, K, maxIter, data, distMethod, seed, threads, verbose) {
    .Call('largeVis_searchTrees', PACKAGE = 'largeVis', threshold, n_trees, K, maxIter, data, distMethod, seed, threads, verbose)
}

fastDistance <- function(is, js, data, distMethod, threads, verbose) {
    .Call('largeVis_fastDistance', PACKAGE = 'largeVis', is, js, data, distMethod, threads, verbose)
}

fastCDistance <- function(is, js, i_locations, p_locations, x, distMethod, threads, verbose) {
    .Call('largeVis_fastCDistance', PACKAGE = 'largeVis', is, js, i_locations, p_locations, x, distMethod, threads, verbose)
}

fastSDistance <- function(is, js, i_locations, j_locations, x, distMethod, threads, verbose) {
    .Call('largeVis_fastSDistance', PACKAGE = 'largeVis', is, js, i_locations, j_locations, x, distMethod, threads, verbose)
}

referenceWij <- function(i, j, d, threads, perplexity) {
    .Call('largeVis_referenceWij', PACKAGE = 'largeVis', i, j, d, threads, perplexity)
}

hdbscanc <- function(edges, neighbors, K, minPts, threads, verbose) {
    .Call('largeVis_hdbscanc', PACKAGE = 'largeVis', edges, neighbors, K, minPts, threads, verbose)
}

checkBits <- function() {
    .Call('largeVis_checkBits', PACKAGE = 'largeVis')
}

checkOpenMP <- function() {
    .Call('largeVis_checkOpenMP', PACKAGE = 'largeVis')
}

sgd <- function(coords, targets_i, sources_j, ps, weights, gamma, rho, n_samples, M, alpha, momentum, seed, threads, verbose) {
    .Call('largeVis_sgd', PACKAGE = 'largeVis', coords, targets_i, sources_j, ps, weights, gamma, rho, n_samples, M, alpha, momentum, seed, threads, verbose)
}

searchTreesCSparse <- function(threshold, n_trees, K, maxIter, i, p, x, distMethod, seed, threads, verbose) {
    .Call('largeVis_searchTreesCSparse', PACKAGE = 'largeVis', threshold, n_trees, K, maxIter, i, p, x, distMethod, seed, threads, verbose)
}

searchTreesTSparse <- function(threshold, n_trees, K, maxIter, i, j, x, distMethod, seed, threads, verbose) {
    .Call('largeVis_searchTreesTSparse', PACKAGE = 'largeVis', threshold, n_trees, K, maxIter, i, j, x, distMethod, seed, threads, verbose)
}

